server:
	\. ./env/bin/activate
	python3 ./manage.py runserver

start:
	\. ./linux_env/bin/activate
	python3 ./manage.py runserver

run:
	python3 ./manage.py runserver

start-win:
	.\env\Scripts\activate
	python ./manage.py runserver

run-win:
	python ./manage.py runserver

migrate-refresh:
	python3 ./manage.py makemigrations
	python3 ./manage.py migrate

migrate-refresh-win:
	python ./manage.py makemigrations
	python ./manage.py migrate

migrate-win:
	python ./manage.py migrate
