# Generated by Django 3.2.5 on 2022-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablature',
            name='audio',
        ),
        migrations.AddField(
            model_name='tablature',
            name='audio_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
