# Generated by Django 4.1.1 on 2022-10-03 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_file_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='datetime',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
